ARG BASE_ALGORAND_VERSION="3.25.0"
FROM algorand/stable:${BASE_ALGORAND_VERSION} AS algorand

FROM gcr.io/distroless/cc AS distroless
COPY --from=algorand --chown=0:0 /root/node/algod /node/algod
COPY --from=algorand --chown=0:0 /root/node/goal /node/goal
COPY --from=algorand --chown=0:0 /root/node/node_exporter /node/node_exporter
ARG NETWORK="testnet"
COPY configuration/${NETWORK}/genesis.json /node/data/genesis.json
